### PR TITLE
chore: add link to newer package

### PR DESCRIPTION
**Pull request by sgammon**
## Summary

Hey party people. Obviously the distribution mechanism for GraalVM has shifted quite a bit recently, and so has the set of conventions and APIs it takes to ship a set of Bazel rules.

After keeping the releases up to date in this package for awhile, I felt a rewrite was needed to keep up with our changing world. [The new package](https://github.com/sgammon/rules_graalvm) supports several new features and is native to Bazel 6 / Bazel 7.

I've tried to maintain backwards compatibility (within the bounds of new conventions). Older versions of the SDK supported through this module are still available through the new package, but the focus will be on the newest GraalVM releases from Oracle and CE in that repo.

Of course, I'm a big fan of this package, having committed to it for quite awhile. But I fear our engagement with GraalVM is drifting from this package's support, and that @andyscott has better things to do than put up with a bunch of messy force-pushed PRs from me. So this PR is 100% optional,  but encouraged just to prevent confusion in the community.

If there is a total revolt over this PR and you guys would _strongly_ rather I keep these extensive changes _here_, in this repo, I'm open to discussing, but as you can tell I'm a little biased toward velocity at this time (just being honest).

**Features added in the new package:**

- Use of GraalVM as a Java toolchain
- Fetch components via `gu` transitively
- Support for Windows
- Support for Bzlmod, and soon a release to BCR
- Refreshed `native_image` rule
- Auto-fetch latest GraalVM SDK and provide your own SHA256
- Support for `target_compatible_with` and a full suite of arch-based SDK registrations (coming soon)
- Matches conventions of newer rules packages
- Compatibility guarantees via Bazel CI and Bzlmod
- Dedicated toolchain types for GraalVM, `native-image` (allows resolving alongside regular JVMs)

## Changelog

- add warning to `README` with link to newer package

### CODE REVIEW

**Comment by andyscott** [comment]
Thanks for contributing, and thanks for the continued work you've put into these rules!

I'm happy to merge this change. As it stands, I don't have time to maintain these rules. If it makes sense, I'm happy to archive them too (or move them to another org).

**Comment by johnynek** [comment]
@andyscott if you want to move them to `bazeltools` org we can take them over there. We are still using these rules at Netflix.

**Comment by johnynek** [comment]
actually, moving the repo to @sgammon seems great! seems like a great steward!

**Comment by sgammon** [comment]
@andyscott / @johnynek thank you! you guys rock. i think archiving the repo is up to you. there is a brightline between the older and newer GVM releases so maybe it's useful on that basis, but I've preserved the older SDK releases in any case to ease transition.

@johnynek if you guys need anything let me know. we're using the new rules and the transition process is outlined in the first release, `0.9.0`. there are some import / rule changes which bring things closer to current rule conventions, but otherwise it should not be a difficult transition at all. if it is, it's a bug.

come to think of it, if you guys aren't on bazel 7 yet, you may see issues. i can prioritize a fix for those if you experience trouble.

**Pull request merged**
