### PR TITLE
Snoble/fix for linux

### PR DESCRIPTION
**Pull request by snoble**
Fix for https://github.com/andyscott/rules_graal/issues/10 lifting behaviour from https://github.com/bazelbuild/rules_go/blob/master/go/private/context.bzl

### CODE REVIEW

**Comment by snoble** [comment]
I don't think the 19.0.0 version will actually work. It might because of the path. But before I invested anytime trying to fix it I figured I'd check if anyone cared.

**Comment by snoble** [comment]
It looks like the CI failure for XCode is not a regression

**Comment by snoble** [comment]
It looks like there are more hermetic options https://github.com/vsco/bazel-toolchains

**Review by andyscott — APPROVED** [review]

**Comment by andyscott** [comment]
CI for the project is currently a bit wonky, unfortunately.

**Pull request merged**
